# adddebug
# Autogenerated from man page /usr/lib/jvm/default/man/man1/adddebug.1.gz
complete -c adddebug -s k -d 'Keep optimisations (do not remove -O[1-9]? flags which are removed by default)'
complete -c adddebug -s r -d 'Recursively search through all subdirectories of the current directory and op…'
complete -c adddebug -s n -d 'compile without NDEBUG and NO_DEBUG being defined (makes kDebug calls work)'
complete -c adddebug -o 'O?' -d 'flags which are removed by default)'

