# cervisia
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cervisia.1.gz
complete -c cervisia -l resolve -d 'Show resolve dialog for the given file'
complete -c cervisia -l log -d 'Show log dialog for the given file'
complete -c cervisia -l annotate -d 'Show annotation dialog for the given file'

