# ec_probe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ec_probe.1.gz
complete -c ec_probe -s h -l help -d '    show this help message and exit'
complete -c ec_probe -s e -l embedded-controller -d '    Specify embedded controller to use [dump, read, write, monitor]     None'
complete -c ec_probe -s i -l interval -d '    Monitored timespan'
complete -c ec_probe -s t -l timespan -d '    Set poll intervall'
complete -c ec_probe -s r -l report -d '    Save all readings as a CSV file'
complete -c ec_probe -s c -l clearly -d '    Blanks out consecutive duplicate readings'
complete -c ec_probe -s d -l decimal -d '    Output readings in decimal format instead of hexadecimal format All input…'

