# evcd2vcd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/evcd2vcd.1.gz
complete -c evcd2vcd -s f -l filename -d 'Specify EVCD input filename'
complete -c evcd2vcd -s h -l help -d 'Show help screen'

