# fixincludes
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fixincludes.1.gz
complete -c fixincludes -s v -l verbose -d 'Verbose mode.  Additional debugging output is written to standard output'
complete -c fixincludes -s e -l experimental -d 'Experimental mode, as described above in detail'
complete -c fixincludes -s m -l modify -d 'As well as writing messages to standard output, actually modify the original …'
complete -c fixincludes -o UQT_NO_COMPAT -d or
complete -c fixincludes -o UKDE_NO_COMPAT -d 'This utility is part of the KDE Software Development Kit.  OPTIONS'

