# fst2vcd
# Autogenerated from man page /usr/share/man/man1/fst2vcd.1.gz
complete -c fst2vcd -l extensionsFr -d 'Emit FST extensions to VCD'
complete -c fst2vcd -s h -l help -d 'Display help then exit'

