# gitg
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gitg.1.gz
complete -c gitg -s h -l help -d 'Show help options'
complete -c gitg -l help-all -d 'Show all help options'
complete -c gitg -l help-gtk -d 'Show GTK+ Options . PP Application Options:'
complete -c gitg -s v -l version -d 'Show the application?s version'
complete -c gitg -l activity -d 'Start gitg with a particular activity'
complete -c gitg -s c -l commit -d 'Start gitg with the commit activity (shorthand for --activity commit)'
complete -c gitg -l no-wd -d 'Do not try to load a repository from the current working directory'
complete -c gitg -l standalone -d 'Run gitg in standalone mode'
complete -c gitg -l display -d 'X display to use'
complete -c gitg -s a -l all -d 'Select all commits by default in the history activity'
complete -c gitg -s b -l branches -d 'Select all branches by default in the history activity'
complete -c gitg -s r -l remotes -d 'Select all remotes by default in the history activity'
complete -c gitg -s t -l tags -d 'Select all tags by default in the history activity'
complete -c gitg -s s -l select-reference -d 'Select the specified reference by default in the history activity'

