# gocryptfs-xray
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gocryptfs-xray.1.gz
complete -c gocryptfs-xray -s 0
complete -c gocryptfs-xray -o encrypt-paths
complete -c gocryptfs-xray -o aessiv
complete -c gocryptfs-xray -o decrypt-paths
complete -c gocryptfs-xray -o dumpmasterkey

