# gocryptfs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gocryptfs.1.gz
complete -c gocryptfs -o fsck
complete -c gocryptfs -s h -o help
complete -c gocryptfs -o hh
complete -c gocryptfs -o info
complete -c gocryptfs -o init
complete -c gocryptfs -o passwd
complete -c gocryptfs -o speed
complete -c gocryptfs -o version
complete -c gocryptfs -o aessiv
complete -c gocryptfs -o deterministic-names
complete -c gocryptfs -o devrandom
complete -c gocryptfs -o hkdf
complete -c gocryptfs -o plaintextnames
complete -c gocryptfs -o raw64
complete -c gocryptfs -o reverse
complete -c gocryptfs -o scryptn
complete -c gocryptfs -o xchacha
complete -c gocryptfs -o allow_other
complete -c gocryptfs -o badname
complete -c gocryptfs -o ctlsock
complete -c gocryptfs -o dev -o nodev
complete -c gocryptfs -s e -o exclude
complete -c gocryptfs -o ew -o exclude-wildcard
complete -c gocryptfs -o exclude-from
complete -c gocryptfs -o exec -o noexec
complete -c gocryptfs -o fg -s f
complete -c gocryptfs -o force_owner
complete -c gocryptfs -o forcedecode
complete -c gocryptfs -o fsname
complete -c gocryptfs -o fusedebug
complete -c gocryptfs -s i -o idle
complete -c gocryptfs -o kernel_cache
complete -c gocryptfs -o ko
complete -c gocryptfs -o longnames
complete -c gocryptfs -o nofail
complete -c gocryptfs -o nonempty
complete -c gocryptfs -o noprealloc
complete -c gocryptfs -o nosuid
complete -c gocryptfs -o nosyslog
complete -c gocryptfs -o notifypid
complete -c gocryptfs -o one-file-system
complete -c gocryptfs -l one-file-system -d 'Mountpoints will appear as empty directories'
complete -c gocryptfs -o rw -o ro
complete -c gocryptfs -o serialize_reads
complete -c gocryptfs -o sharedstorage
complete -c gocryptfs -o suid
complete -c gocryptfs -o zerokey
complete -c gocryptfs -o config
complete -c gocryptfs -o cpuprofile
complete -c gocryptfs -s d -o debug
complete -c gocryptfs -o extpass -o extpass
complete -c gocryptfs -o fido2
complete -c gocryptfs -o masterkey
complete -c gocryptfs -o memprofile
complete -c gocryptfs -s o
complete -c gocryptfs -o openssl
complete -c gocryptfs -o passfile -o passfile
complete -c gocryptfs -s q -o quiet
complete -c gocryptfs -o trace
complete -c gocryptfs -o wpanic

