# id3cp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/id3cp.1.gz
complete -c id3cp -s 1 -l v1tag -d 'Render only the id3v1 tag'
complete -c id3cp -s 2 -l v2tag -d 'Render only the id3v2 tag'
complete -c id3cp -s h -l help -d 'Display help and exit'
complete -c id3cp -s v -l version -d 'Display version information and exit SEE ALSO id3convert(1), id3info(1), id3v…'

