# id3convert
# Autogenerated from man page /usr/lib/jvm/default/man/man1/id3convert.1.gz
complete -c id3convert -s 1 -l v1tag -d 'Render only the id3v1 tag'
complete -c id3convert -s 2 -l v2tag -d 'Render only the id3v2 tag'
complete -c id3convert -s s -l strip -d 'Strip, rather than render, the tags'
complete -c id3convert -s p -l padding -d 'Use padding in the tag'
complete -c id3convert -s h -l help -d 'Display help and exit'
complete -c id3convert -s v -l version -d 'Display version information and exit'

