# id3tag
# Autogenerated from man page /usr/lib/jvm/default/man/man1/id3tag.1.gz
complete -c id3tag -s 1 -l v1tag -d 'Render only the id3v1 tag'
complete -c id3tag -s 2 -l v2tag -d 'Render only the id3v2 tag'
complete -c id3tag -s h -l help -d 'Display help and exit'
complete -c id3tag -s v -l version -d 'Display version information and exit'
complete -c id3tag -s a -l artist -d 'Set the artist information'
complete -c id3tag -s s -l song -d 'Set the song title information'
complete -c id3tag -s A -l album -d 'Set the album title information'
complete -c id3tag -s c -l comment -d 'Set the comment information'
complete -c id3tag -s C -l desc -d 'Set the comment description'
complete -c id3tag -s g -l genre -d 'Set the genre number'
complete -c id3tag -s y -l year -d 'Set the year'
complete -c id3tag -s t -l track -d 'Set the track number'
complete -c id3tag -s T -l total -d 'Set the total number of tracks on the album'

