# kalzium
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kalzium.1.gz
complete -c kalzium -l molecule -d 'Open the given molecule file in cml, xyz, ent, pdb, alc, chm, cdx, cdxml, c3d…'

