# kbackup
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kbackup.1.gz
complete -c kbackup -s v -l version -d 'Displays version information'
complete -c kbackup -s h -l help -d 'Displays help on commandline options'
complete -c kbackup -l help-all -d 'Displays help including Qt specific options'
complete -c kbackup -l qmljsdebugger -d 'Activates the QML/JS debugger with a specified port'
complete -c kbackup -l script -d 'Script to run after finishing one archive slice'
complete -c kbackup -l auto -d 'Automatically run the backup with the given profile and terminate when done'
complete -c kbackup -l autobg -d 'Automatically run the backup with the given profile in the background (withou…'
complete -c kbackup -l verbose -d 'In autobg mode be verbose and print every single filename during backup'
complete -c kbackup -l forceFull -d 'In auto/autobg mode force the backup to be a full backup instead of acting on…'
complete -c kbackup -l author -d 'Show author information'
complete -c kbackup -l license -d 'Show license information'
complete -c kbackup -l desktopfile -d 'The base file name of the desktop entry for this application'

