# ktouch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ktouch.1.gz
complete -c ktouch -l resource-editor -d 'Launch the course and keyboard layout editor'
complete -c ktouch -s I -l import-path -d 'Prepend the path to the list of QML import paths'

