# lxt2vcd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lxt2vcd.1.gz
complete -c lxt2vcd -s l -l lxtname -d 'Specify LXT2 input filename'
complete -c lxt2vcd -s o -l output -d 'Specify optional VCD output filename'
complete -c lxt2vcd -s f -l flatearth -d 'Emit flattened hierarchies'
complete -c lxt2vcd -s n -l notruncate -d 'Do not shorten bitvectors'
complete -c lxt2vcd -s h -l help -d 'Display help then exit'

