# meinproc5
# Autogenerated from man page /usr/lib/jvm/default/man/man1/meinproc5.1.gz
complete -c meinproc5 -o h--help
complete -c meinproc5 -o v--version -d 'Show version information.  APPLICATION OPTIONS'
complete -c meinproc5 -l cache -d 'Create a cache file for the document'
complete -c meinproc5 -l check -d 'Check the document for validity'
complete -c meinproc5 -s o -l output -d 'Output whole document to file'
complete -c meinproc5 -l stdout -d 'Output whole document to stdout'
complete -c meinproc5 -l stylesheet -d 'Stylesheet to use'
complete -c meinproc5 -l srcdir -d 'Set the root directory to look for kdoctools'
complete -c meinproc5 -l param -d 'Set parameters to pass to the stylesheet'

