# nbfc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nbfc.1.gz
complete -c nbfc -s h -l help -d '    show this help message and exit'
complete -c nbfc -l version -d '    show program\'s version number and exit [start, stop, restart, status, con…'
complete -c nbfc -s e -l enabled -d '    Start in enabled mode (default)'
complete -c nbfc -s r -l readonly -d '    Start in read-only mode'
complete -c nbfc -s a -l all -d '    Show service and fan status (default)'
complete -c nbfc -s s -l service -d '    Show service status'
complete -c nbfc -s f -l fan -d '    Show fan status'
complete -c nbfc -s w -l watch -d '    Show status periodically'
complete -c nbfc -s l -l list -d '    List all available configs (default)'
complete -c nbfc -l set -d '    Set a config'
complete -c nbfc -l apply -d '    Set a config and enable fan control'
complete -c nbfc -l recommend -d '    List configs which may work for your device'
complete -c nbfc -l auto -d '    Set fan speed to \'auto\''
complete -c nbfc -l speed -d '    Set fan speed to PERCENT'

