# nvme-huawei-list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-huawei-list.1.gz
complete -c nvme-huawei-list -s o -l output-format -d 'Set the reporting format to normal or json'

