# nvme-netapp-ontapdevices
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-netapp-ontapdevices.1.gz
complete -c nvme-netapp-ontapdevices -s o -l output-format -d 'Set the reporting format to normal (default), column, or json'

