# nvme-intel-temp-stats
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-intel-temp-stats.1.gz
complete -c nvme-intel-temp-stats -s b -l raw-binary -d 'Print the raw temperature stats log buffer to stdout'

