# obenergy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obenergy.1.gz
complete -c obenergy -s v -d 'Verbose: print out all individual energy interactions'
complete -c obenergy -o ff -d 'Select the forcefield El EXAMPLES Pp View the possible options, including ava…'

