# obminimize
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obminimize.1.gz
complete -c obminimize -s n -d 'Specify the maximum number of steps (default=2500)'
complete -c obminimize -o cg -d 'Use conjugate gradients algorithm (default)'
complete -c obminimize -o sd -d 'Use steepest descent algorithm'
complete -c obminimize -s c -d 'Set convergence criteria (default=1e-6)'
complete -c obminimize -o ff -d 'Select the forcefield El EXAMPLES Pp View the possible options, including ava…'

