# obprobe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obprobe.1.gz
complete -c obprobe -s s -d 'Set the resolution of the grid (stepsize)'
complete -c obprobe -s p -d 'Set the padding -- extra distance on each side of the box formed by the molec…'

