# obrms
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obrms.1.gz
complete -c obrms -s f -d 'use only the first structure in the reference file (otherwise the nth molecul…'
complete -c obrms -s m -d 'Compute the minimum RMSD achievable by applying a rigid-body transformation t…'
complete -c obrms -s x -d 'Compute all n^2 RMSDs between molecules of the reference file'
complete -c obrms -s s -d 'Separate reference file into constituent molecules (disconnected fragments) a…'
complete -c obrms -s o -d 'Re-oriented test structure output (used with -m) EXAMPLES "obrms ref'

