# obspectrophore
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obspectrophore.1.gz
complete -c obspectrophore -s i -d 'Specifies the molecular input file from which Spectrophores are to be calcula…'
complete -c obspectrophore -s n -d 'Specifies the kind of normalization that should be performed'
complete -c obspectrophore -s a -d 'Specifies the required accuracy expressed as the angular stepsize'
complete -c obspectrophore -s s -d 'Specifies the kind of cages that should be used in terms of the underlying po…'
complete -c obspectrophore -s r -d 'Specifies the required resolution expressed as a real positive number'
complete -c obspectrophore -s u -d 'Display implementation details'
complete -c obspectrophore -s h -d 'Display help message.  El SEE ALSO obabel 1'

