# obthermo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/obthermo.1.gz
complete -c obthermo -l symm -d 'override symmetry number used in input file'
complete -c obthermo -l nrot -d 'number of rotatable bonds for conformational entropy'
complete -c obthermo -l dbdt -d 'temperature derivative of second virial coefficient for cp calculation'
complete -c obthermo -l kj -d 'output kJ/mol related units (default kcal/mol) El SEE ALSO obabel 1'

