# pruneemptydirs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pruneemptydirs.1.gz
complete -c pruneemptydirs -s f -d 'Actually perform the deletions instead of just printing them out'

