# psensor-server
# Autogenerated from man page /usr/lib/jvm/default/man/man1/psensor-server.1.gz
complete -c psensor-server -s h -l help -d 'display this help and exit'
complete -c psensor-server -s v -l version -d 'display version information and exit'
complete -c psensor-server -s p -l port -d 'webserver port'
complete -c psensor-server -s w -l wdir -d 'directory containing webserver pages'
complete -c psensor-server -s d -l debug -d 'set the debug level, integer between 0 and 3'
complete -c psensor-server -s l -l log-file -d 'set the log file to PATH'
complete -c psensor-server -l sensor-log-file
complete -c psensor-server -l sensor-log-interval -d 'SENSOR LOG FILE'

