# psensor
# Autogenerated from man page /usr/lib/jvm/default/man/man1/psensor.1.gz
complete -c psensor -s h -l help -d 'display this help and exit'
complete -c psensor -s v -l version -d 'display version information and exit'
complete -c psensor -s u -l url -d 'the URL of the psensor-server, example: http://hostname:3131'
complete -c psensor -s n -l new-instance -d 'force the creation of a new Psensor application'
complete -c psensor -s d -l debug -d 'set the debug level, integer between 0 and 3 REPORTING BUGS Report bugs to: j…'

